Нестеренко Андрей. Лабораторная работа №2. Лабораторная работа №2. Вариант 5

In [1]:
import math
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
from scipy import integrate

import sympy

Step 1

In [2]:
array = np.random.randint(0, 8, (6, 6))
array

array([[3, 4, 1, 7, 0, 3],
       [6, 2, 1, 6, 0, 3],
       [1, 2, 0, 4, 4, 7],
       [5, 5, 0, 0, 4, 1],
       [7, 0, 4, 7, 6, 7],
       [0, 0, 0, 6, 0, 7]])

In [3]:
slice_arr_1 = array[-2:]
slice_arr_1

array([[7, 0, 4, 7, 6, 7],
       [0, 0, 0, 6, 0, 7]])

In [4]:
slice_arr_2 = array[:, :2]
slice_arr_2

array([[3, 4],
       [6, 2],
       [1, 2],
       [5, 5],
       [7, 0],
       [0, 0]])

Step 2

In [5]:
# Векторное умножение матриц
C = np.dot(slice_arr_1, slice_arr_2)
C

array([[102,  71],
       [ 30,  30]])

In [6]:
np.matmul(slice_arr_1, slice_arr_2)

array([[102,  71],
       [ 30,  30]])

In [7]:
print(slice_arr_1)
print(slice_arr_2)

[[7 0 4 7 6 7]
 [0 0 0 6 0 7]]
[[3 4]
 [6 2]
 [1 2]
 [5 5]
 [7 0]
 [0 0]]


In [8]:
A = slice_arr_1
B = slice_arr_2

In [9]:
C = np.zeros((A.shape[0], B.shape[1]))

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(A.shape[1]):
            C[i][j] += A[i][k] * B[k][j]

C            

array([[102.,  71.],
       [ 30.,  30.]])

In [10]:
def vec_mul(a: np.ndarray, b: np.ndarray):
    result = np.zeros((a.shape[0], b.shape[1]))
    if a.shape[1] == b.shape[0]:
        for i in range(a.shape[0]):
            # iterate through columns of Y
            for j in range(b.shape[1]):
                result[i,j] = np.matmul(a[i, :], b[:, j])

    return result

Step 3

In [39]:
def norm_infinity(arr_str):
    print(f"Вектор-строка 1x10 из случайных целых чисел - {arr_str}")
    print(f"Отсортированный вектор - {sorted(arr_str)}")
    print(f"{arr_str[-1]}, норма от бесконечности - {np.linalg.norm(arr_str, ord=np.inf)}")
    return(arr_str)

arr_str = norm_infinity(np.random.randint(0, 10, (10)))    

Вектор-строка 1x10 из случайных целых чисел - [6 7 1 7 9 5 2 9 9 9]
Отсортированный вектор - [1, 2, 5, 6, 7, 7, 9, 9, 9, 9]
9, норма от бесконечности - 9.0


Step 4


In [25]:
arr_norm_F = np.random.randint(0, 10, (5, 5))
arr_norm_F

array([[9, 0, 9, 2, 7],
       [7, 7, 0, 7, 5],
       [0, 9, 4, 1, 2],
       [9, 3, 6, 1, 7],
       [8, 4, 6, 4, 8]])

In [37]:
def f_norm(a: np.ndarray):
    res = 0
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            res+=a[i][j]**2
    return math.sqrt(res)

In [38]:
print(f_norm(arr_norm_F))
print(np.linalg.norm(arr_norm_F, ord='fro'))

29.34280150224242
29.34280150224242


Step 5

Step 6


In [41]:
arr_norm_F

array([[9, 0, 9, 2, 7],
       [7, 7, 0, 7, 5],
       [0, 9, 4, 1, 2],
       [9, 3, 6, 1, 7],
       [8, 4, 6, 4, 8]])

In [52]:
import numpy as np

def lu_decomposition(matrix):
    n = matrix.shape[0]
    L = np.eye(n)
    U = matrix.copy()

    for k in range(n-1):
        for i in range(k+1, n):
            L[i, k] = U[i, k] / U[k, k]
            U[i, k:] -= L[i, k] * U[k, k:]

    return L, U

# Создание матрицы
A = arr_norm_F
# Вычисление LU разложения
L, U = lu_decomposition(A)

# Проверка результатов
result = np.dot(L, U)
print(result)

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

Step 7

In [54]:
def qr_decomposition(matrix):
    Q, R = np.linalg.qr(matrix)
    return Q, R

# Создание матрицы
A = arr_norm_F

# Вычисление QR разложения
Q, R = qr_decomposition(A)

# Проверка результатов
result = np.dot(Q, R)
print(result)

result_np = np.linalg.qr(A)
print(result_np)

[[ 9.00000000e+00 -2.60364540e-16  9.00000000e+00  2.00000000e+00
   7.00000000e+00]
 [ 7.00000000e+00  7.00000000e+00  1.25006131e-15  7.00000000e+00
   5.00000000e+00]
 [ 0.00000000e+00  9.00000000e+00  4.00000000e+00  1.00000000e+00
   2.00000000e+00]
 [ 9.00000000e+00  3.00000000e+00  6.00000000e+00  1.00000000e+00
   7.00000000e+00]
 [ 8.00000000e+00  4.00000000e+00  6.00000000e+00  4.00000000e+00
   8.00000000e+00]]
(array([[-0.54272042,  0.33311365, -0.46781967,  0.36979302, -0.48876142],
       [-0.42211588, -0.40062742,  0.714083  ,  0.24119735, -0.30532796],
       [-0.        , -0.84820605, -0.51258281, -0.04862578, -0.12426138],
       [-0.54272042,  0.0503783 , -0.00584421, -0.8383399 ,  0.00828409],
       [-0.48241815, -0.08087945, -0.09195076,  0.31606756,  0.80769895]]), array([[-16.58312395,  -6.51264504, -11.03531521,  -6.51264504,
        -13.56801051],
       [  0.        , -10.61062932,  -0.57780824,  -3.2595102 ,
         -1.66214115],
       [  0.        ,   0. 